import type { Config } from "tailwindcss";

export default {
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface-container-low": "#1b1b1b",
        "tertiary-fixed": "#c6e7ff",
        "surface-tint": "#a5c8ff",
        "on-tertiary-container": "#e6f4ff",
        "on-primary-container": "#ecf1ff",
        "on-primary-fixed-variant": "#004784",
        "on-error-container": "#ffdad6",
        "tertiary-container": "#0076a3",
        "surface-variant": "#353535",
        "on-secondary-fixed-variant": "#314867",
        "inverse-surface": "#e2e2e2",
        "inverse-on-surface": "#303030",
        "surface-container": "#1f1f1f",
        "on-primary-fixed": "#001c3a",
        "secondary-fixed": "#d4e3ff",
        "primary-container": "#206fc0",
        "surface-bright": "#393939",
        "outline-variant": "#414751",
        "on-surface": "#e2e2e2",
        "surface-container-highest": "#353535",
        "surface-container-lowest": "#0e0e0e",
        "primary-fixed-dim": "#a5c8ff",
        "on-secondary-container": "#a0b6db",
        "on-secondary": "#1a314f",
        "primary": "#a5c8ff",
        "on-tertiary": "#00344b",
        "primary-fixed": "#d4e3ff",
        "inverse-primary": "#005fad",
        "surface-container-high": "#2a2a2a",
        "surface": "#131313",
        "on-background": "#e2e2e2",
        "secondary": "#b1c8ed",
        "tertiary-fixed-dim": "#81cfff",
        "error": "#ffb4ab",
        "on-surface-variant": "#c1c7d3",
        "background": "#131313",
        "tertiary": "#81cfff",
        "secondary-container": "#314867",
        "on-tertiary-fixed": "#001e2d",
        "on-secondary-fixed": "#011c39",
        "outline": "#8b919d",
        "secondary-fixed-dim": "#b1c8ed",
        "surface-dim": "#131313",
        "error-container": "#93000a",
        "on-tertiary-fixed-variant": "#004c6b",
        "on-error": "#690005",
        "on-primary": "#00315e"
      },
      fontFamily: {
        headline: ["var(--font-newsreader)", "serif"],
        body: ["var(--font-inter)", "sans-serif"],
        label: ["var(--font-inter)", "sans-serif"],
        kannada: ["var(--font-noto-kannada)", "sans-serif"],
      },
      borderRadius: {
        DEFAULT: "0.25rem", 
        lg: "0.5rem", 
        xl: "0.75rem", 
        "2xl": "1rem",
        "3xl": "1.5rem",
        full: "9999px"
      },
    },
  },
  plugins: [],
} satisfies Config;
